### ISSUE TITLE
Add info about available keyboard shortcuts

### ISSUE THREAD

**Issue by ganigeorgiev** [ganigeorgiev/presentator#15]

**Comment by danicatalan** [comment]
@ganigeorgiev which keyboard shortcuts are currently available on the app?

It would be great to have this info inside the app, but anyway is enough if we can have a preview on this issue to start using them.

Anyway you did a great work, congrats!

**Comment by ganigeorgiev** [comment]
@danicatalan  Here is a short list:

| Action                         | Trigger               |
|:-------------------------------|:-----------------------|
| Bulk Screens selection         | **shift** + **left click** on screen list item |
| Bulk Hotspots selection        | **shift** + **left click** on hotspot |
| Quick Hotspot duplicate        | **ctrl**  + **left click** on hotspot |
| Closing popups, popovers, etc. | **esc**                |

This weekend I'll try to find some time and will define them + will add some new ones (suggestions are also welcome).

**Comment by danicatalan** [comment]
Very useful the Bulk Screens ones, thanks! 👍

**Comment by ganigeorgiev** [comment]
Just added a blog post about them - https://presentator.io/en/blog/hidden-features.
