### ISSUE TITLE
No comments information

### ISSUE THREAD

**Issue by ghs** [ganigeorgiev/presentator#16]
There are version and screens counters per each project within the list of projects, but anything about the comments added to a screen so users can see if there are some or even new, unseen has been added (this exists as a list on the dashboard).

**Comment by ganigeorgiev** [comment]
If a project/screen has unseen comment(s) it should have a yellow bell at it top-right corner.

I'll consider adding a comments counter near the versions and screens ones.

**Comment by ganigeorgiev** [comment]
Due to performance issues with the eager loading (Yii currently has problem supporting nested via relations), this enhancement will be implemented eventually in future releases. I will close the issue for now, but please let me know if someone else insist it.
