### ISSUE TITLE
Information about shared project

### ISSUE THREAD

**Issue by ghs** [ganigeorgiev/presentator#17]
When somebody is viewing a shared project, there is no information about it or the owner. Will be good to get some heading with something like "You are currently viewing PROJECT by OWNER".
Also in such cases, if the user is signed in currently could get additional link/button for "back to your account" as now happens that there is no way to go back to the account when viewing a shared project.

**Comment by ganigeorgiev** [comment]
Implemented with the latest new screens control panel updates.
