### ISSUE TITLE
Shared project autoplay, controls and all screens layout

### ISSUE THREAD

**Issue by ghs** [ganigeorgiev/presentator#18]
Based on the project and the presentation itself users could want to just click a button and play automatically all screens. Something like that: http://www.jssor.com/demos/image-gallery.slider + the progress indicator for better experience http://devrama.com/static/devrama-slider/example-html-content

Other similar (presentation) tools and applications (PDF viewers, Flickr, most of JS sliders) use to have all screens or pages on a side or below with a scrolling option. This gives the user a possibility to look for another screen or page while keeping the actual one visible.

And in general, the current controls or new ones which could be added should be more visible and within a separate from the screen element. Based on the detail of the screen image and the size of the actual computer screen the current controls are almost invisible for the eye.

**Comment by ganigeorgiev** [comment]
Auto play button with progressbar will be added in v1.0.1.

The control panel design was suggested during beta (back then it was a control bar very similar to InVision) by other users and the idea behind that was to minimize any additional visible elements to the preview page and to make it as not intrusive as possible. I'll consider, before v1.0.1, to create a poll with possible design implementations of the control panel.

**Comment by ganigeorgiev** [comment]
New and even more descreet control panel was implemented with the latest changes.
For greater simplicity and to prevent controls confusion the auto play button is not implemented, but if anyone else thinks it will be useful, feel free to reopen the issue.
