### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by ghs** [ganigeorgiev/presentator#19]
Was looking around the FAQs and playing within the app, but couldn't understand the idea about the versions of a project.
From the perspective of a designer, usually a project is presented to a client and this makes annotations and based on them another version is created and so on until an agreement that everything is fine now.
But here comes a problem (and maybe something related with [my previous issue](https://github.com/ganigeorgiev/presentator/issues/12)):

- in case the client agrees on X screens, for the next version the designer will have to upload them again for the next presentation. kinda pain in the but based on how many have to upload. here is missing something like copy screen to another version or even project, or create new version from another (like git repos)
- clients always want to see how was the old screen when the new and modified one is presented with the new version. as there is no possibility to link with the hotspots or make a comparison, the client or the designer will have to open another browser or tap with the previous version in order to see it.

**Comment by ganigeorgiev** [comment]
Hm, there is an option to move screen(s) from one version to another, but copy/duplicate is not available. I'll consider adding it in v1.0.1 release.

For the comparison option - I'll check and review other similar apps to see how to better implement the UI/UX for that feature.

**Comment by ghs** [comment]
Just discovered the "move to version" :)

**Comment by ganigeorgiev** [comment]
@ghs Version naming support was added in the latest v1.0.1. Copy/Duplicate is also implemented but requires some additional tests and will be included in the next release.
