### ISSUE TITLE
Visible checkbox on larger screens

### ISSUE THREAD

**Issue by ghs** [ganigeorgiev/presentator#2]
On 2560x1440 screen "#registerform-terms" is visible at the very left side. This is due the [left:-999px](https://github.com/ganigeorgiev/presentator/blob/master/app/web/scss/_forms.scss#L365) if not mistaken :)

![captura de pantalla 2017-04-18 a las 14 34 48](https://cloud.githubusercontent.com/assets/94248/25130916/39ce2dba-2444-11e7-9d62-dab5e105f4b6.png)

**Comment by ganigeorgiev** [comment]
I pushed a quick fix. Note that it doesn't use `visibility:hidden` or `display:none` because of older IE 
and Safari versions that prevent them to receive events from hidden inputs.

**Comment by ghs** [comment]
Sure! It was about "always" using much larger values when trying to "hide" something :)

**Comment by ghs** [comment]
Ops, one more! :)
Same happens with the radios
![captura de pantalla 2017-04-21 a las 11 33 31](https://cloud.githubusercontent.com/assets/94248/25272040/93e4a4de-2686-11e7-8c9f-dae16bbe1b5c.png)

**Comment by ganigeorgiev** [comment]
Thanks, should be fixed with a6681528d216d5c85c47b8a199260d7e6c7f9b56.
