### ISSUE TITLE
Extremely poor contrast

### ISSUE THREAD

**Issue by jorunn** [ganigeorgiev/presentator#20]
Text in the GUI is generally light gray on even lighter gray. There is barely any contrast and it is very hard to read.
![screenshot 2017-04-24 15 23 56](https://cloud.githubusercontent.com/assets/5385683/25339218/2a1fab56-2902-11e7-80b1-3447578d29c0.png)

**Comment by ganigeorgiev** [comment]
Thanks for reporting the issue. I've increased the contrasts by darkening the default text color with nearly 5% (a3d4186eb17c9907919cc37c39dadf5e107dcbf4) but it depends a lot on your monitor color settings (I've tested it on standard lcd laptop screen and on calibrated TN and IPS monitors and it looks ok to me).

If anyone experience the same issue, please reopen the ticket.

**Comment by ganigeorgiev** [comment]
@garrett Thanks for the detailed info. A slightly improvement was included in v1.11.3 release.

I've recently started working on the design for v2 and will definitely keep in mind the accessibility.
