### ISSUE TITLE
Cant upload any images (add screens)

### ISSUE THREAD

**Issue by flatulent** [ganigeorgiev/presentator#21]
Mac Safari Version 10.1 (12603.1.30.0.34)
Add screen, select image. Nothing happens. Tried drag and drop, again nothing happens. Tried on Chrome (on Mac) and it works!
This is a really useful piece of software, Well done guys. Awesome work.

**Comment by ganigeorgiev** [comment]
It seems that Safary doesn't fully support [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) objects.

It should be fixed with ff4362a0f1e53cb7643f6cd3655198a49604a24a. Please reopen if you still experience issues with screens uploading.
