### ISSUE TITLE
no Bower

### ISSUE THREAD

**Issue by Ladydinde** [ganigeorgiev/presentator#22]
After a fresh installation, (everything goes fine) accessing the url cause this error : 

`[Thu Apr 27 12:06:36.506386 2017] [:error] [pid 16947] [client 78.194.214.172:33158] An Error occurred while handling another error:\nexception 'yii\\base\\InvalidParamException' with message 'The file or directory to be published does not exist: /home/mockup/public_html/vendor/bower/jquery/dist' in /home/mockup/pu.....`

I have no bower folder in vendor... so something goes wrong during installation.

**Comment by Ladydinde** [comment]
I rename *bower-assets* to *bower* and it seems to work now...

**Comment by ganigeorgiev** [comment]
I am glad to hear that you manage to run it.

This seems to be related to Composer assets plugin settings (in some versions the default bower directory seems to be named bower-assets or sth like that). To ensure that the bower will be installed in the correct vendor folder I've added a `.bowerrc` with predefined direcotry path - https://github.com/ganigeorgiev/presentator/commit/55131822bbb2babe164e85de6635b8aa13a0168b.

To test it -  delete the `vendor` directory and run again `composer install`. Let me know if you still encounter the issue.
