### ISSUE TITLE
Can easyer change name or just presentator.io

### ISSUE THREAD

**Issue by Dryusdan** [ganigeorgiev/presentator#25]
Hi   
I create [Dockerfile ](https://github.com/Dryusdan/Dockerfiles/tree/master/presentator) for Presentator and I found in mail, usage condition etc...  "presentator.io", "team presentator.io". So, it's possible to change presentator.io to another name with database, file or environnement ? It's just for limit break with an update :)

(Woops, sorry for my english :x )

**Comment by ganigeorgiev** [comment]
@Dryusdan The domain name was removed from the project title - https://github.com/ganigeorgiev/presentator/commit/058b99a9a5587bf55a123a8e070c4d652f2279e9.

**Comment by Dryusdan** [comment]
Okay, thank you :)
