### ISSUE TITLE
Provide direct url to comment mode

### ISSUE THREAD

**Issue by MDXDave** [ganigeorgiev/presentator#32]

**Comment by ganigeorgiev** [comment]
Implemented in `develop` - https://github.com/ganigeorgiev/presentator/commit/b1a01d52b7c35f2232fc88d74be0362b98e02e7d

To enable it add `?m=comments` (or `?m=preview` for preview mode) to the Project preview link, eg. `https://app.presentator.io/en/mySlug?m=comments`.

Will be included in the next release (v1.1.0)

**Comment by ganigeorgiev** [comment]
Deployed on production.
