### ISSUE TITLE
Screen size handling for projects/boards

### ISSUE THREAD

**Issue by Nick-codable** [ganigeorgiev/presentator#33]
## Problem
When you share a link with someone and that person opens a link on a device that has a smaller screen size than the width of the original design (often, mobile phone, tablets, or generally smaller size netbook or laptop), it is quite painful to view the design/project. 

## Solution
Ability to set the width of the project/board to the width of the browser. This potentially could be an option within settings for the project/board (could be like a toggle between screen overflow / scale down to browser width). Seriously, this is widely implemented in similar services.

## Future use
This would be also useful for the comments mode, as now comments also overflow on the mobile device. A lot of clients are lazy and want to approve/comment stuff on their mobile phones (and its hard to educate them to do this on larger screens)

**Comment by ganigeorgiev** [comment]
@Nick-codable Thanks for the suggestion. I'll add an option in the project preview bar for toggling between the current behavior and a "fit in browser" mode (this will be implemented in v.1.2.0).

**Comment by ganigeorgiev** [comment]
A partial solution to autofit the screen image to the browser width is implemented and included in v1.5.0 release:
![Fit to screen toggle](https://i.cubeupload.com/9E2WIx.png)

However I admit that the platform is not optimized for mobile users and currently the interface requires some modifications (especially the comments section) that will be handled in another ticket.
