### ISSUE TITLE
Suggestion: Show Filename or Title

### ISSUE THREAD

**Issue by Wiredframe** [ganigeorgiev/presentator#37]
It would be awesome to show the filename of uploaded screens for better management. Even better: Allow custom screen titles.

Keep up the great work! Presentator rocks!

**Comment by ganigeorgiev** [comment]
@Wiredframe There is already an option to define custom screen title from the screen settings popup (click on the gear icon located in the top screen bar):
![Image of Yaktocat](https://i.cubeupload.com/4AlKxl.png)

**Comment by Wiredframe** [comment]
Awesome, thanks for the hint. It would be great if the Title would be shown in the screens overview, too. 👍 
![image](https://user-images.githubusercontent.com/13737875/30716184-64662b2c-9f19-11e7-8678-0729f61dfe0a.png)

**Comment by Wiredframe** [comment]
Great to hear! Thanks! I'm trying to spread the word about this awesome project on Twitter.

**Comment by ganigeorgiev** [comment]
Merged in master. Will be included in v1.4.0 release.

**Comment by Wiredframe** [comment]
Thanks! Very helpful!
