### ISSUE TITLE
how to install it on CPanel

### ISSUE THREAD

**Issue by alahwany** [ganigeorgiev/presentator#42]
Hello,

can you please help me to install it on my CPanel ?

**Comment by ganigeorgiev** [comment]
@alahwany The installation instructions are located at: https://github.com/ganigeorgiev/presentator/blob/master/docs/start-installation.md.

I suggest you to create a git repo on your server for easier future upgrades, since the project is still under active development (new versions are released almost every month).

If you don't have SSH access you could setup first the project locally and then upload the files manually to the server.

p.s. Don't forget to choose the correct environment during _Step 5_ from the installation instructions.

**Comment by alahwany** [comment]
thank you very much for your reply 

i like this script so much and i hope if there any installed version already to download it and upload it on my CPanel and adjust only configuration for DB.  
if you can make this for me i will be very happy and send the link on my mail " alahwany at gmail dot com"
thank you again for this script. and i will try with it.

**Comment by ganigeorgiev** [comment]
@alahwany I've mailed you a link to a zip with a built project and a sql script with the minumum db structure.

Note that you still need to manually configure the mail, db and other environment specific parameters in `/common/config/params-local.php` and `/common/config/main-local.php`.

When I manage to find some free time, I'll try to create a gui installer/update tool but that will be handled in another ticket - #43.

**Comment by alahwany** [comment]
@ganigeorgiev  thank you very much for your help.

i will try to run it on my cpanel with my sql and i hope to finish the gui installer/update tool soon because most users using shared hosting like cpanel so it's better if you did it.

thank you very much

**Comment by claudioBarreira89** [comment]
Hi @ganigeorgiev, 
Any chance I can also have an already installed version? I'm having some issues with my shared host, this would help a lot.  
If that was possible this would be the email to send to 'claudio dot barreira89 at gmail dot com'

Thank you for your help and all the great work,
Claudio.

**Comment by ganigeorgiev** [comment]
For 1.6+ version you can download an archive with built in vendor dependencies from here - https://presentator.io/downloads/latest. Also make sure to follow the [installation instructions](https://github.com/ganigeorgiev/presentator/blob/master/docs/start-installation.md).

**Comment by smth** [comment]
Wondering if it would be feasible to have Presentator added to [Softaculous](https://www.softaculous.com/softaculous/apps). That would probably be the easiest way to install on CPanel hosting.

**Comment by ganigeorgiev** [comment]
@smth Unfortunately I rarely use CPanel (and never Softaculous) so I'm not sure how actually the integration part could be done (Presentator v2 comes with a lot of user options that need to be manually configured).

Please note that this issue and the comments above are for Presentator v1.
For Presentator v2 I recommend you to follow the [presentator-starter instrictions](https://github.com/presentator/presentator-starter). It shouldn't be very difficult to install it on a shared hosting, just make sure to copy the project files outside your `public_html` folder and to point your document root to `/path/to/starter/web`
