### ISSUE TITLE
Update instructions

### ISSUE THREAD

**Issue by Arjoni** [ganigeorgiev/presentator#46]
Please provide update instructions.

**Comment by ganigeorgiev** [comment]
@Arjoni currently the easiest way to update the platform is to setup git on your environment and to checkout the latest master over ssh:
```bash
# fetch latest changes 
$ git pull origin master 

# apply app DB migrations
$ php yii migrate/up

# apply tests DB migrations (optional)
$ php yii_test migrate/up
```

I'll try to eliminate this inconvenience in the next release (**1.6**) which main target is issue https://github.com/ganigeorgiev/presentator/issues/43.

**Comment by Arjoni** [comment]
Should I wait until 1.6 to upgrade?

**Comment by ganigeorgiev** [comment]
@Arjoni It depends whether you need the latest features (you could check the [release notes](https://presentator.io/en/blog) posts). The update tool/command will be implemented with fallback support for older versions (1.0+), so the direct update to 1.6 wouldn't break anything.

Please note that, based on the current project planning, in the best scenario 1.6 will be released in the end of January 2018.

**Comment by Arjoni** [comment]
Thanks! One other stupid question, where can I see the version that I am 
using? I have installed it some weeks ago and I am not sure.

**Comment by ganigeorgiev** [comment]
@Arjoni That's actually a very good suggestion. The platform itself doesn't store any info about the current running version other than the git tag (if you deployed with git). Since you've installed it some weeks ago probably you are using v.1.4.0/1.5.0.

The version number will be included in the next release.

**Comment by ganigeorgiev** [comment]
@Arjoni An update command is added with v1.6.0. Check the [update instructions](https://github.com/ganigeorgiev/presentator/blob/master/docs/start-updates.md) for more info how to migrate.
