### ISSUE TITLE
Problem add admin

### ISSUE THREAD

**Issue by USherbrookeFCNC** [ganigeorgiev/presentator#47]
I want to add an admin to my project and i'm not able to...

When I go into «Managed admin» and I write an email into the text field a box open and says : No result found. And nothing happen. 

Is it a bug? How can I add an admin other way?
Thanks

**Comment by ganigeorgiev** [comment]
@USherbrookeFCNC  Just tested it and everything seems to be OK.

Only registered users could be added as project administrators. Also please note that the "fuzzyUsersSearch" setting in the production setup is disabled and you have to type the full email address before a match is returned.

If you still encounter any issues, please send me the user email address you are trying to add at support@presentator.io.
