### ISSUE TITLE
Cannot run the application through Apache

### ISSUE THREAD

**Issue by imswill** [ganigeorgiev/presentator#52]
Thanks for the great app!

Unfortunately, I cannot run your application in my machine, following the instruction described in the link below.
https://github.com/ganigeorgiev/presentator/blob/master/docs/start-installation.md#installation

I managed to install the application through the graphics installer and it seemed to work.
However, when I tried to access the home (http://my-domain/presentator in my case) I always got an 404 error from the page saying "The requested URL /presentator/en/entrance/ was not found on this server".

[/path/to/presentator/app/web] ls
assets  css  fonts  images  index.php  install  js  robots.txt  scss  uploads

Looking at /app/web directory, there's no directory such called "en".
I guess the url goes to the controller and the view file "/app/views/site/entrance.php" should be rendered, but somehow it never works.

My httpd.conf looks like this.
Alias /presentator "/path/to/presentator/app/web/"

<Directory /path/to/presentator/app/web>
      Options Indexes FollowSymLinks MultiViews
      AllowOverride None
      Require all granted
</Directory>
(Also, tried VirtualHost instead, but no use..)

The below is from /path/to/presentator/app/runtime/logs/
    'CONTEXT_PREFIX' => '/presentator'
    'CONTEXT_DOCUMENT_ROOT' => '/path/to/presentator/app/web/'
    'SERVER_ADMIN' => 'root@localhost'
    'SCRIPT_FILENAME' => '/path/to/presentator/app/web/index.php'
    'REMOTE_PORT' => '2200'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'REQUEST_METHOD' => 'GET'
    'QUERY_STRING' => ''
    'REQUEST_URI' => '/presentator/'
    'SCRIPT_NAME' => '/presentator/index.php'
    'PHP_SELF' => '/presentator/index.php'
(No error message in the file)

I tested this on RHEL 6.6 (httpd 2.2) and CentOS 7.3 (httpd 2.4), but same result.
I also tried both "For Production (GUI Installer)" and "For Development (Manual)" in the guide.

Could you help me on this?

Thanks!

**Comment by ganigeorgiev** [comment]
Probably this is a server misconfiguration. Are you trying to install it on production or local machine?

Try changing the **AllowOverride** option value to **All**, restart the apache server and try again (it is possible that it prevent the app .htaccess rules to be applied).
Run also from the console the requirements.php file located in the project root directory to check if there is a missing extension or sth like that.

**Comment by ganigeorgiev** [comment]
In addition, make sure that the mod_rewrite module in your httpd config is uncommented (should be something like `LoadModule rewrite_module modules/mod_rewrite.so`)

**Comment by imswill** [comment]
#1
- I tried "AllowOvverride All", but it still doesn't work.
- LoadModule ... mod_rewrite.so is not commented out

#2
$ php requirements.php
...
PDO MySQL extension: OK

PDO PostgreSQL extension: WARNING!!!
Required by: All DB-related classes
Memo: Required for PostgreSQL database.

Memcache extension: OK

APC extension: WARNING!!!
Required by: ApcCache

GD PHP extension with FreeType support: OK

ImageMagick PHP extension with PNG support: OK

Expose PHP: WARNING!!!
Required by: Security reasons
Memo: "expose_php" should be disabled at php.ini

PHP allow url include: OK

PHP mail SMTP: OK

------------------------------------------
Errors: 0   Warnings: 3   Total checks: 24

The warnings could be related to it?

#3
I sent phpinfo file to support@presentator.io as it's too large to put here.

Thanks!

**Comment by ganigeorgiev** [comment]
The phpinfo and the requirements output looks ok.

One of the thing I can think of at the moment is that for some reason the htaccess file doesn't work in your case.
First, to ensure that the .htaccess is not ignored, try to add some invalid characters at the top of it, eg. "test." ("Internal Server Error" or sth. similar should be returned).
If your are not using HTTPS comment the auto HTTPS redirect rule (https://github.com/ganigeorgiev/presentator/blob/master/app/web/.htaccess#L3).

The other thing, if I've understood correctly, is that you are trying to load the application from a sub-folder domain like path (eg. yoursite.com/presentator/) and I'm not sure that the rewrite rules are properly configured to work in this case. I'll check it a little later and try to simulate it locally.

**Comment by ganigeorgiev** [comment]
Since I can't simulate your environment setup locally, if possible you could send me a temporary ssh credentials to your server at support [at] presentator.io and I'll try to debug it.

With the next release I'll try to prepare an official docker image that hopefully will make the installation on vps/dedicated servers easier.

**Comment by imswill** [comment]
I finally figured this out!

.htaccess file was the problem as you commented.
Here's the configurations that work for me.

**httpd.conf (httpd 2.2)**
Listen 8080
<VirtualHost *:8080>
        DocumentRoot "/path/to/presentator/app/web"

        <Directory /path/to/presentator/app/web>
             Options FollowSymLinks MultiViews
             AllowOverride All
             Order allow,deny
             Allow from all
        </Directory>
</VirtualHost>

Following 2 lines should be replaced with "Require all granted" for httpd 2.4.
Order allow,deny
Allow from all

**/path/to/presentator/app/web/.htaccess**
RewriteEngine on

# Redirect to https
#RewriteCond %{REMOTE_ADDR} !=127.0.0.1
#RewriteCond %{HTTPS} !=on
#RewriteRule ^.*$ https://%{SERVER_NAME}%{REQUEST_URI} [R,L]

# If a directory or a file exists, use it directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# Otherwise forward it to index.php
RewriteRule . index.php

Thanks for your help!

**Comment by nitinyjadhav7** [comment]
how to find default username and password for login

**Comment by ganigeorgiev** [comment]
@nitinyjadhav7 You have to register manually a new user via the registration form after the installation completes. Check also - [Post installation](https://github.com/ganigeorgiev/presentator/wiki/Post-installation).

**Comment by ikantthink** [comment]
Since you're on the subject of .htaccess...
https://www.nginx.com/resources/wiki/start/topics/examples/likeapache-htaccess/

I find nginx far simpler and easier to use than Apache. For those looking to install with nginx, you'll need to add this to your server block (virtual host):
```
location / {
  if (!-e $request_filename){
    rewrite ^(.*)$ /index.php;
  }
}
```

**Comment by nuts7** [comment]
> Since you're on the subject of .htaccess...
> https://www.nginx.com/resources/wiki/start/topics/examples/likeapache-htaccess/
> 
> I find nginx far simpler and easier to use than Apache. For those looking to install with nginx, you'll need to add this to your server block (virtual host):
> 
> ```
> location / {
>   if (!-e $request_filename){
>     rewrite ^(.*)$ /index.php;
>   }
> }
> ```

Hi 
I installed app and it is working fine but I registered one user and not able to login now.
It shows invalid Username/Password but i am entering correct  username password.

**Comment by nuts7** [comment]
> @nitinyjadhav7 You have to register manually a new user via the registration form after the installation completes. Check also - [Post installation](https://github.com/ganigeorgiev/presentator/wiki/Post-installation).

I am not able to login .
Please find below details:
'mailer' => [
                        'class' => 'common\components\swiftmailer\CMailer',
                        'viewPath' => '@common/mail',
                        'useFileTransport' => true, ]

**Comment by ganigeorgiev** [comment]
@nuts7 After registering via the registration form, you should receive an activation link to your email.

Since it seems that you using file transport, probably you are receiving the emails as html files located in `app/runtime/mail`.

You have to set `useFileTransport` to false and configure a transport for the mailer to send real emails.
eg.
```php
'mailer' => [
    'class' => 'common\components\swiftmailer\CMailer',
    'viewPath' => '@common/mail',
    'useFileTransport' => false,
    'transport' => [
        'class'      => 'Swift_SmtpTransport',
        'host'       => 'test.myhost.net',
        'username'   => 'no-reply@myhost.net',
        'password'   => '123456',
        'port'       => '465',
        'encryption' => 'ssl',
    ]
]
```
