### ISSUE TITLE
BCMath error while registering a new account

### ISSUE THREAD

**Issue by imswill** [ganigeorgiev/presentator#53]
While creating a new account in the "Register" form, I got an error saying:
`The BCMath functions must be enabled to use the NTLM authenticator.`

I was able to go through this by installing php56-bcmath.x86_64 as below.
`sudo yum install php56-bcmath.x86_64`

I don't know if this is just my case, but the library would be good to be added to "requirements.php".

Thanks!

**Comment by ganigeorgiev** [comment]
@imswill Thanks for the info. I'll check it and consider updating the requirements file.
