### ISSUE TITLE
add Albanian language to transifex

### ISSUE THREAD

**Issue by elioqoshi** [ganigeorgiev/presentator#57]
I'd like to help with translations to Albanian but it's currently not available in Transifex. Could you add Albanian? (sq) Happy to help translating then :)

**Comment by ganigeorgiev** [comment]
I'm glad to hear that you are willing to help. I've just added the language and sent you an invention though Transifex.

**Comment by elioqoshi** [comment]
@ganigeorgiev I just finished translating 100% into Albanian. Can you review all strings and confirm them? Or you can make me a reviewer and I can do that.

There were some typos in the English versions which I fixed in the Albanian one. I am unsure of a few strings and need to see it in action in Albanian to see if they make sense, but I think that it should be okay for a first version :)

**Comment by elioqoshi** [comment]
Oh, I also used the non-formal way of addressing the user, as I saw that's how it was done in German too.

**Comment by ganigeorgiev** [comment]
Thank you once again for your help. The translations will be deployed with v1.7 release (mid april https://github.com/ganigeorgiev/presentator/milestone/9). Еven if there are slight discrepancies, they could be corrected with the next iteration.

**Comment by elioqoshi** [comment]
Thanks, looking forward!

**Comment by ganigeorgiev** [comment]
@elioqoshi The Albanian translations are available in production with v.1.7.0 release.

If you find anything wrong feel free to update the translations through Transifex (Transifex comment notifications are a little buggy, so if you need a context for some of the messages, please mention me with _@gani.georgiev_).
