### ISSUE TITLE
Create an official docker image

### ISSUE THREAD

**Issue by ganigeorgiev** [ganigeorgiev/presentator#59]

**Comment by der-On** [comment]
:+1:

**Comment by der-On** [comment]
I can try on this if you like. I was already starting to get it work with docker anyway.

**Comment by der-On** [comment]
I would recommend creating a seperate docker repository for this that checks out a version of presentator.io

**Comment by der-On** [comment]
The one question that resides is if we should provide two docker images one for the app and one for the API? Or should we create one that maps `/app` to the app and `/api` to the api?

**Comment by ganigeorgiev** [comment]
I don't think there is that much difference between the two approaches.
Personally I would go with only 1 image, otherwise you will have to handle 2 instances of the application with the same configurations and volume mounted.

I've just created an empty repo - https://github.com/ganigeorgiev/presentator-docker so you can push your implementation there (of course, only if you have time and want to take care of the task).

**Comment by der-On** [comment]
Thanks. For now I will try to dockerize this repo for local development. Then I will move to create the docker-image in the other repo.

**Comment by der-On** [comment]
Sorry for not beeing active on this so far. As we now have a working docker dev environment I should be able to come up with a docker image soon I hope. Thank you for your work.

**Comment by ganigeorgiev** [comment]
@der-On I've recently pushed a robust version in https://github.com/ganigeorgiev/presentator-docker. The image is also available in [Docker Hub](https://hub.docker.com/r/ganigeorgiev/presentator/).

This days I'll try to find some free time and add more detailed instructions for deploying it on cloud hostings like DigitalOcean or Vultr.

If you have any suggestions, feel free to open an issue in the [presentator-docker](https://github.com/ganigeorgiev/presentator-docker) repo.

**Comment by der-On** [comment]
@ganigeorgiev Thank you so much for this work. I'm sorry I wasn't able to help here. I will test the docker setup soon I guess and give feedback.
