### ISSUE TITLE
API slug for building links preview

### ISSUE THREAD

**Issue by ucodi** [ganigeorgiev/presentator#62]
Hello,

I can't find the slug for building links of project preview in the response of project view with the API.
https://api.presentator.io/doc/index.html#api-Projects-view

**Comment by ganigeorgiev** [comment]
This is missing. I'll add it in v1.8.0 release.

**Comment by ganigeorgiev** [comment]
@ucodi Implemented in v1.8.0 as part of the Project model response (see the project "previews" property).
