### ISSUE TITLE
Enable CORS for ajax request to the api

### ISSUE THREAD

**Issue by ucodi** [ganigeorgiev/presentator#64]
https://enable-cors.org/server_apache.html

**Comment by ganigeorgiev** [comment]
Oops, this is a server misconfiguration. I'll try to update it later this day.

**Comment by ganigeorgiev** [comment]
Fixed it on the production server of api.presentator.io.
I've also added it in `.htaccess` in the develop branch and with v1.8.0 will be enabled by default.

**Comment by ucodi** [comment]
Thank you.

**Comment by ucodi** [comment]
Sorry,
but it seems to miss a configuration to allow the x-access-token in the response Header from ajax call :thinking: 

Access-Control-Allow-Headers: x-access-token maybe ?

**Comment by ganigeorgiev** [comment]
@ucodi Just added it. Everything should be ok now.

**Comment by ucodi** [comment]
All works fine now 😀

Thank you !
