### ISSUE TITLE
can't install presentator on php 7.0

### ISSUE THREAD

**Issue by mokra** [ganigeorgiev/presentator#68]
First of all thank you very much for this project.
I would really love to start testing and contributing - but I can't install it.

I sais that I need PHP 7.1 but I only have 7.0
Is it true? I saw in your requirements description, that 7.0 should work

**Comment by ganigeorgiev** [comment]
Just tested it. Indeed, there is an error with phpunit/codeception in php7.0.
This weekend I will try to review all dependencies and their requirementents in details and eventually will upload a fix as v1.8.1 release.

Meanwhile, If you want to install the project locally, I recommend you to use the integrated Docker dev environment - https://github.com/ganigeorgiev/presentator/wiki/Develop-with-Docker.

**Comment by ganigeorgiev** [comment]
@mokra [v1.8.1](https://github.com/ganigeorgiev/presentator/releases/tag/v1.8.1) with regenerated `composer.lock` file is released. The automation tests and the installation process were tested with php5.6, php7.0 and php7.1.

If you still are unable to install/setup the project, please comment/reopen the issue.

**Comment by mokra** [comment]
thanks!
The yii file was also missing in the root folder.
