### ISSUE TITLE
Add comment

### ISSUE THREAD

**Issue by Laul0** [ganigeorgiev/presentator#73]
When I'm creating a project and image, it could be useful to add description on them.

## Settings preview

| Images | Projects |
|---------|---------|
| ![screen shot 2018-07-27 at 11 01 09](https://user-images.githubusercontent.com/15279205/43312376-5fe3da9c-918d-11e8-96c9-95232bf1a366.png)| ![screen shot 2018-07-27 at 11 08 56](https://user-images.githubusercontent.com/15279205/43312569-fc12fc86-918d-11e8-81e9-462d2e218494.png)|

## Dashboard preview

| Home | Project |
|-------|--------|
| ![screen shot 2018-07-27 at 11 15 52](https://user-images.githubusercontent.com/15279205/43312953-040abe32-918f-11e8-961f-7c4c546169b0.png) | ![screen shot 2018-07-27 at 11 20 30](https://user-images.githubusercontent.com/15279205/43313216-ba740d4a-918f-11e8-8dd6-fe2c5bec6564.png) |

**Comment by ganigeorgiev** [comment]
@Laul0 Thanks for the mockups.

Unfortunately I don't think that this feature will be very useful and it will results in unnecessary complication of the interface.

At least when I and my coworkers interact in Presentator, we usually use for the project title the company name and the task itself (eg. "X-company redesign") and I think that it is enough explanatory. Similarly for the project screens - we usually use titles like "Homepage (light layout)", "UI elements list", etc.

For now I will close the issue, but if someone else think that this feature should be implemented, please add your concerns as a comment.
