### ISSUE TITLE
Proposal : GitLab/GitHub OAuth

### ISSUE THREAD

**Issue by Laul0** [ganigeorgiev/presentator#79]
# Current behavior

An user can create an account with his mail address and password or link his account with Facebook.

# Expected behavior

Because we work with GitLab (online and self-hosted) or Github like lot of developper and designers, add the OAuth with this tools will be really useful.

GitHub OAuth is already embedded in Yii OAuth but not GitLab. Here an URL to add GitLab OAuth capabilities : https://packagist.org/packages/omines/oauth2-gitlab

**Comment by ganigeorgiev** [comment]
Implemented in v1.11.0 release.
