### ISSUE TITLE
Docker version is not up-to-date

### ISSUE THREAD

**Issue by Laul0** [ganigeorgiev/presentator#84]
# Summary

Docker presentator environment

# Current behavior

I did a docker pull latest and with specified version to 1.11 and the real version still to be 1.10.
I can't use the GitLab OAuth and I can't use the latest features

# Expeced behavior

Perform a docker pull latest version and use presentator 1.11.

**Comment by ganigeorgiev** [comment]
Ops, sorry for that. I've updated the package version in the Dockerfile (https://github.com/ganigeorgiev/presentator-docker).
Also a new minor version v1.11.1 was released this morning that includes a fix for the Google OAuth client (https://github.com/yiisoft/yii2-authclient/issues/245).
