### ISSUE TITLE
Plaintext mail lags of activation link

### ISSUE THREAD

**Issue by SISheogorath** [ganigeorgiev/presentator#93]
I just signed up for an account and due to fact that I read my email in plaintext, I also got the activation mail in plaintext. It's wonderful that you provide a plaintext version of the email, but I noticed a little problem:

![image](https://user-images.githubusercontent.com/8719867/52197121-b7f78680-285e-11e9-83eb-f185285b6d7b.png)

Everything blue and underlined is a link, everything else is text only. As you may notice, the mail content lags of an activation link. No worries, when using the HTML version of the mail it works perfectly. It's just that you send a plaintext version of the mail as well and you simple don't provide the most important piece of information in that version. Would be great when it could be managed to get this into the plaintext version :smile: 

Thanks!

**Comment by ganigeorgiev** [comment]
Should be fixed in v1.13.0.
